language: c
dist: xenial
services:
  - xvfb
compiler:
  - gcc
addons:
  apt:
    update: true
    packages:
      - qemu
script: mkdir build && cd build && cmake .. && make && xvfb-run --server-args="-screen 0 1024x768x24" make test
